import { UserProvider } from '@auth0/nextjs-auth0/client';

import './globals.css';

export const metadata = {
  title: 'Wardrobe Wiz',
  description: 'Generated by Next.js', // Fix this add a better description
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body>{children}</body>
      </UserProvider>
    </html>
  );
}
