import { UserProvider } from '@auth0/nextjs-auth0/client';

import './globals.css';
import BottomNavBar from './components/navBar/NavBar';
import HamburgerMenu from './components/hamburgerMenu/HamburgerMenu';

export const metadata = {
  title: 'Wardrobe Wiz',
  description: 'Generated by Next.js', // Fix this add a better description
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <HamburgerMenu />
        <body>{children}</body>
        <BottomNavBar />
      </UserProvider>
    </html>
  );
}
