debug: true
server:
  port: 3000
  error:
    include-message: always
spring:
  sql:
    init:
      platform: postgresql
      mode: never
    output:
      ansi:
        enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/wardrobewiz
    username: user
    password: pass
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
